{% set name = "nbproject" %}
{% set version = "0.10.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/nbproject-{{ version }}.tar.gz
  sha256: a56ad4e363154579af4f6491a121a380cad8e617bbcb31471ae214dfd7815a82

build:
  entry_points:
    - nbproject = nbproject.__main__:main
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 2

requirements:
  host:
    - python
    - flit-core >=3.2,<4
    - pip
  run:
    - python
    - pydantic <2.0.0
    - pyyaml
    - packaging
    - orjson
    - ipylab
    - importlib-metadata
    - stdlib-list  # [py<310]
    - lamin_utils >=0.5.0

test:
  imports:
    - nbproject
  commands:
    - pip check
    - nbproject --help
  requires:
    - pip

about:
  home: https://github.com/laminlabs/nbproject
  summary: 'nbproject: Manage Jupyter notebooks.'
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - berombau
